server:
  port: 18084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

  zipkin:
    base-url: http://localhost:9411
    discovery-client-enable: true
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456


  redis:
    host: 168.192.142.128
    port: 6379
feign:
  sentinel:
    enable: true
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.atguigu.gmall.sms.entity
  global-config:
    db-config:
      id-type: auto
